"""update users auth fields

Revision ID: f1f64c3684a3
Revises: b1c142b6b492
Create Date: 2026-03-10 20:38:35.461270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f64c3684a3'
down_revision: Union[str, Sequence[str], None] = 'b1c142b6b492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("collections_owner_id_fkey", "collections", type_="foreignkey")
    op.drop_constraint("items_owner_id_fkey", "items", type_="foreignkey")
    op.drop_constraint("following_followee_id_fkey", "following", type_="foreignkey")
    op.drop_constraint("following_follower_id_fkey", "following", type_="foreignkey")

    op.alter_column(
        "users",
        "id",
        existing_type=sa.VARCHAR(length=120),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.alter_column('collections', 'owner_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="owner_id::uuid")
    op.alter_column('following', 'followee_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="followee_id::uuid")
    op.alter_column('following', 'follower_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="follower_id::uuid")
    op.alter_column('items', 'owner_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="owner_id::uuid")

    op.create_foreign_key(
        "collections_owner_id_fkey",
        "collections",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "items_owner_id_fkey",
        "items",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "following_followee_id_fkey",
        "following",
        "users",
        ["followee_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "following_follower_id_fkey",
        "following",
        "users",
        ["follower_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("collections_owner_id_fkey", "collections", type_="foreignkey")
    op.drop_constraint("items_owner_id_fkey", "items", type_="foreignkey")
    op.drop_constraint("following_followee_id_fkey", "following", type_="foreignkey")
    op.drop_constraint("following_follower_id_fkey", "following", type_="foreignkey")

    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False,
               postgresql_using="id::varchar")
    op.alter_column('items', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False,
               postgresql_using="owner_id::varchar")
    op.alter_column('following', 'follower_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False,
               postgresql_using="follower_id::varchar")
    op.alter_column('following', 'followee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False,
               postgresql_using="followee_id::varchar")
    op.alter_column('collections', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False,
               postgresql_using="owner_id::varchar")

    op.create_foreign_key(
        "collections_owner_id_fkey",
        "collections",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "items_owner_id_fkey",
        "items",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "following_followee_id_fkey",
        "following",
        "users",
        ["followee_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "following_follower_id_fkey",
        "following",
        "users",
        ["follower_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
